async function main() {
  try {
  } catch (error: any) {
    console.error(`Error: ${error.message}`);
  }
}
main();
